repos:
  - repo: local
    hooks:
      - id: lint-format-cmake
        name: LintFormatCmake
        entry: ./scripts/lint-and-format.sh
        language: script
      - id: googletest
        name: Google Test
        entry: ./run.sh
        args:
          - "SlowboostTests"
          - "Debug"
        language: script
