repos:
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.10
    hooks:
      - id: cmake-format
      - id: cmake-lint
  - repo: local
    hooks:
      - id: googletest
        name: Google Test
        entry: ./test.sh
        language: script